openapi: 3.0.0
info:
  title: "Pricing API"
  description: "API para consultar precios de productos"
  version: "1.0.0"

servers:
  - url: http://localhost:8080
    description: "Servidor local"

paths:
  /prices:
    get:
      summary: "Obtener precio aplicable"
      parameters:
        - name: productId
          in: query
          required: true
          description: "ID del producto"
          schema:
            type: integer
        - name: brandId
          in: query
          required: true
          description: "ID de la cadena"
          schema:
            type: integer
        - name: date
          in: query
          required: true
          description: "Fecha en formato yyyy-MM-dd'T'HH:mm:ss"
          schema:
            type: string
      responses:
        "200":
          description: "Precio encontrado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    type: integer
                  brandId:
                    type: integer
                  priceList:
                    type: integer
                  startDate:
                    type: string
                  endDate:
                    type: string
                  price:
                    type: number
        "404":
          description: "Precio no encontrado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                  error:
                    type: string
        "500":
          description: "Error interno del servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                  error:
                    type: string